CREATE TABLE IF NOT EXISTS "PacienteLente" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "creadoEn" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "RecetaLente" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "pacienteLenteId" INTEGER NOT NULL,
    "fecha" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "RecetaLente_pacienteLenteId_fkey" FOREIGN KEY ("pacienteLenteId") REFERENCES "PacienteLente" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "FotoRecetaLente" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "recetaLenteId" INTEGER NOT NULL,
    "foto" TEXT NOT NULL,
    "observaciones" TEXT NOT NULL DEFAULT '',
    CONSTRAINT "FotoRecetaLente_recetaLenteId_fkey" FOREIGN KEY ("recetaLenteId") REFERENCES "RecetaLente" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
